version: "3.8"

services:
  web:
    build: ./
    command: gunicorn --config gunicorn_config.py --reload app:app
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - mongodb-service
      - redis-service
    container_name: App

  mongodb-service:
    image: mongo:5.0.2
    ports:
      - "27018:27017"
    logging:
      driver: none
    volumes:
      - mongodb_data:/data/db
    container_name: MongoDB

  redis-service:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    container_name: Redis

volumes:
  mongodb_data:
