version: "3.8"

services:
  web:
    build: ./
    command: gunicorn --config gunicorn_config.py app:app
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - mongodb-service
      - redis-service

  mongodb-service:
    image: mongo:5.0.2
    ports:
      - "27018:27017"
    logging:
      driver: none
    volumes:
      - mongodb_data:/data/db

  redis-service:
    image: redis
    restart: always
    ports:
      - "6380:6379"

volumes:
  mongodb_data:
